### ISSUE TITLE
Addon incompatible with Ember 2.2.0-beta.2

### ISSUE THREAD

**Issue by cbuquicchio** [auth0/auth0-ember-simple-auth#11]
I am installing the addon using ember-cli as is outlined in the readme
Here is the error I am getting:
simple-auth.amd.js:375 Uncaught TypeError: container.lookup is not a function

**Comment by brancusi** [comment]
Hi @cbuquicchio, sorry to hear that. Which version of ember are you running? We need to update the docs since there are some breaking changes in the last push.

**Comment by cbuquicchio** [comment]
@brancusi I am running 2.2.0-beta.2

**Comment by brancusi** [comment]
@cbuquicchio, can you try to reinstall. Please follow the new instructions outlined for `ember >= 2.x.x`

I noticed some issues with the last push, also this has not been republished to npm, so it needs to have the github url in for the npm install.

Please let me know if this works for you and if not please paste in any errors.

I reinstalled from scratch and got it working but I am running ember-cli from source so I'm not sure if there are any differences there.

Thanks.

**Comment by cbuquicchio** [comment]
@brancusi it's working!
Thanks for the help.

**Comment by brancusi** [comment]
Glad to hear it!
