### ISSUE TITLE
Fix Jquery Ember issue

### ISSUE THREAD

**Issue by Annyv2** [auth0/auth0-ember-simple-auth#19]
Ember is not able to handle Jquery's new version. To fix this bug, instead of having "jquery": "^1.11.1". It should be "jquery": "1.11."

**Comment by brancusi** [comment]
@Annyv2, what's the status with this? Which versions does this break, are others experiencing an issue with this as well?

**Comment by Annyv2** [comment]
It still happens to me but probably because I haven't updated my ember. I think we can close this issue https://github.com/ember-cli/ember-cli/issues/5316
