### ISSUE TITLE
session not available in templates

### ISSUE THREAD

**Issue by artburkart** [auth0/auth0-ember-simple-auth#22]
I think there might be a small piece missing from the README. 

Somewhere, it should probably point out that the `{{#if session.isAuthenticated}}` bit won't work unless you run the following first:

```console
ember g controller application
```

And put the following into it:

```js
import Ember from 'ember';

const {inject} = Ember;

export default Ember.Controller.extend({
  session: inject.service()
});
```

At least this is the case for Ember 2.x

Cheers!

**Comment by brancusi** [comment]
Thanks @artburkart, good point. Would you be willing to take a crack at this?

**Comment by artburkart** [comment]
Sure, np

**Comment by brancusi** [comment]
Thanks for the PR!
