### ISSUE TITLE
Can't get custom authorizer to fire

### ISSUE THREAD

**Issue by nerdybeast** [auth0/auth0-ember-simple-auth#34]
I, for the life of me, cannot get a custom authorizer to fire... I have followed the instructions on the readme for this repo but have had no luck. Here is my current setup:

config/environment.js
```
ENV['ember-simple-auth'] = {
    authenticationRoute: 'index',
    routeAfterAuthentication: 'protected',
    routeIfAlreadyAuthenticated: 'protected'
};

ENV['auth0-ember-simple-auth'] = {
    clientID: "...",
    domain: "sith-oath.auth0.com"
};

ENV['contentSecurityPolicy'] = {
    'font-src': "'self' data: https://*.auth0.com",
    'style-src': "'self' 'unsafe-inline'",
    'script-src': "'self' 'unsafe-eval' https://*.auth0.com",
    'img-src': '*.gravatar.com *.wp.com data:',
    'connect-src': "'self' http://localhost:* https://sith-oath.auth0.com"
};
```

routes/application.js
```
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
	actions: {
		login () {
			var lockOptions = { authParams: { scope: 'openid'} };
			//this is an exact replica of the default authenticator found in the readme: https://github.com/auth0/auth0-ember-simple-auth#custom-authenticators
			//this is located in my project at: authenticators/sith-custom.js
			this.get('session').authenticate('authenticator:sith-custom', lockOptions);
		},
		logout () {
			this.get('session').invalidate();
		}
	}
});
```

authorizers/sith-custom.js
```
import Ember from 'ember';
import BaseAuthorizer from 'ember-simple-auth/authorizers/base';

export default BaseAuthorizer.extend({
	//cannot get this method to fire
	authorize: function(sessionData, block) {
		console.info('authorizers/sith-custom sessionData =>', sessionData);
		console.info('authorizers/sith-custom block =>', block);
	}
});
```

Your readme talks about setting the `crossOriginWhitelist` but ember simple auth removed support for this in version 1.0 which you guys seem to be using.

I have tried putting this code in several places but no matter where it is, I am still unable to get the authorizer to fire:
```
this.get('session').authorize('authorizer:sith-custom', (headerName, headerValue) => {
    //...
});
```

I am using ember-cli v2.4.0.

Any help will be greatly appreciated!

**Comment by afour-arpits** [comment]
I had same issue. You need to udate your Application Adapter. Import DataAdapterMixin into the adapter and provide custom authorizer as below. This will automatically trigger custom authorizer whenever any server call occur. 

../app/adapters/your-app-adapter.js -

import Ember from 'ember';
import DS from 'ember-data';
import config from '../config/environment';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.RESTAdapter.extend(DataAdapterMixin,{
  authorizer: 'authorizer:sith-custom',
  namespace: 'api',
  ...
  pathForType: function(type) {
    ...
  }
  ...
});

**Comment by nerdybeast** [comment]
I was still unable to get this authorizer to fire when I made api calls not using ember data. I ended up abandoning this approach and went another direction.
