### ISSUE TITLE
Prepare support for Ember Simple Auth 1.0

### ISSUE THREAD

**Issue by thijsvdanker** [auth0/auth0-ember-simple-auth#9]
Ember Simple Auth is working on a 1.0 release.
One of the main reasons I'm looking forward to it is because it has support for Ember 2.0+

There is currently a jj-abrams branch for the 1.0 version development (see https://github.com/simplabs/ember-simple-auth/pull/602)

It would be great if the Auth0 plugin could work with the ESA 1.0 version when it is released.

I know there is at least 1 breaking change:
The namespace for the library changed from `simple-auth` to `ember-simple-auth`.
There is a demo application for using ESA 1.0 here https://github.com/simplabs/ember-simple-auth/tree/jj-abrams/tests/dummy

**Comment by sprockow** [comment]
+1

**Comment by dobesv** [comment]
The new ember-simple-auth has been released now, and now this library doesn't work properly any more.

**Comment by thijsvdanker** [comment]
There is a pull-request here #10. If we can get that in, that would be great.

**Comment by thijsvdanker** [comment]
#10 is merged in so this one can be closed
